# Generated by Django 4.2.1 on 2023-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_send_bod_chatbot_send_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=500)),
                ('bot_reply', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Chatbot',
            new_name='dialogue',
        ),
    ]
